### ISSUE TITLE
Too many instances of Angular Language Server

### ISSUE THREAD

**Issue by indiescripter** [eclipse/wildwebdeveloper#509]
Release info:
Eclipse IDE for JavaScript and Web Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200

Host OS: Linux Mint

Ok so I have exactly one `.ts` file open for editing in Eclipse and after about 10 seconds the editor becomes unresponsive, even taking several seconds to move the caret one character position with the left/right arrow keys.

Having a peek in a terminal, wow, there are many node processes active:

```shell
$ ps -A | grep node
  12112 ?        00:00:00 node
  12119 ?        00:00:00 node
  12123 ?        00:00:00 node
  12134 ?        00:00:00 node
  12143 ?        00:00:00 node
  12147 ?        00:00:05 node
  12158 ?        00:00:00 node
  12162 ?        00:00:05 node
  12170 ?        00:00:05 node
  12177 ?        00:00:05 node
  12190 ?        00:00:05 node
  12195 ?        00:00:00 node
  12203 ?        00:00:05 node
  12215 ?        00:00:05 node
  12224 ?        00:00:07 node
  12231 ?        00:00:07 node
  12237 ?        00:00:07 node
  12245 ?        00:00:07 node
  12246 ?        00:00:07 node
  12259 ?        00:00:07 node
  12261 ?        00:00:07 node
  12273 ?        00:00:00 node
  12280 ?        00:00:00 node
  12287 ?        00:00:00 node
  12288 ?        00:00:00 node
  12289 ?        00:00:00 node
  12291 ?        00:00:00 node
  12315 ?        00:00:00 node
```

Upon closing the Eclipse projects containing said TypeScript source file and checking running node processes again:

$ ps -A | grep node
$

No node processes running.

Opening project and the same TypeScript source file again and back to where before:

$ ps -A | grep node
  12695 ?        00:00:00 node
  12703 ?        00:00:00 node
  12713 ?        00:00:00 node
  12722 ?        00:00:00 node
  12730 ?        00:00:00 node
  12739 ?        00:00:01 node
  12744 ?        00:00:00 node
  12753 ?        00:00:01 node
  12766 ?        00:00:01 node
  12775 ?        00:00:01 node
  12784 ?        00:00:01 node
  12789 ?        00:00:00 node
  12802 ?        00:00:01 node
  12807 ?        00:00:00 node
  12821 ?        00:00:00 node
  12828 ?        00:00:00 node
  12829 ?        00:00:00 node
  12831 ?        00:00:00 node
  12849 ?        00:00:00 node
  12856 ?        00:00:00 node
  12863 ?        00:00:00 node
  12870 ?        00:00:00 node
  12877 ?        00:00:00 node
  12883 ?        00:00:00 node
  12890 ?        00:00:00 node
  12898 ?        00:00:00 node
  12905 ?        00:00:00 node
  12912 ?        00:00:00 node

I haven't dug deeper yet though this problem has been happening since the first time I used Eclipse 2020 with wildwebdeveloper.  Unfortunately I've had to switch to vscode which I don't particularly like (probably because of muscle memory developed over 20 years of using Eclipse).

Just in case it matters, I'm developing in a monorepo environment like [lerna](https://github.com/lerna/lerna) consequently there are about 17 `tsconfig.json` files in the overall Eclipse project. These represent the 17 or so subprojects in the "lerna" monorepo. 

It's just occurred to me now as I type up this issue that possibly the TypeScript language server business is starting up a few node processes for each tsconfig in the project. Is this possible/likely?  Even so, I would expect that the language server should only start node processes for source files that are open.

Also sometimes I close the monorepo project and check in the terminal and all these node processes are still running. The only way to get rid of these, short of manually killing them in the terminal is to restart Eclipse.

I find it hard to believe that I'm the only one experiencing this issue & hope this report is useful.

**Comment by mickaelistria** [comment]
>  I would expect that the language server should only start node processes for source files that are open.

Yes, that's indeed what's intended, but something seems to have change in the Angular Language Server: it now starts 1 instance per project.
I'll investigate that.
In the meantime, if you're not using Angular, you can go to Preferences > Language Servers and uncheck the lines that mention Angular Language Server, then restart your IDE.

**Comment by mickaelistria** [comment]
This should be fixed with https://github.com/eclipse/wildwebdeveloper/pull/520 , which is soon to be available in snapshots.

**Comment by mickaelistria** [comment]
This is now fixed. Please try https://download.eclipse.org/wildwebdeveloper/snapshots/ and reopen with details if this doesn't fix the issue.

**Comment by indiescripter** [comment]
Hey thanks so much @mickaelistria.
Sorry I have not been around this last week to contribute any more insightful comments but sounds like you have it sorted.
I'll test out the snapshot once past the weekend and hope to confirm your fix.
All best wishes to you wherever you are in the world in these crazy times. Take care, Justin.

**Comment by indiescripter** [comment]
Hi @mickaelistria,

Post weekend I've had a chance to examine this fix per [snapshot](https://download.eclipse.org/wildwebdeveloper/snapshots/).

I'm super pleased to confirm that matters are much much better now.

By opening & closing projects and individual TypeScript source files and side-by-side examining running node processes in the terminal via `ps -A | grep node`, node processes appear and disappear as is reasonably expected to be correct behaviour.

Great work. Thank you very much for your efforts.

There is so much that I like about Eclipse that together with the Wild Web Developer addon brings the platform closer to being a viable IDE alternative to VSCode!

**Comment by indiescripter** [comment]
Hello again @mickaelistria,

After a day of using this fix I regret to inform that something is still not quite right. The problem with too many instances of node running has definitely gone away but unfortunately it is now taking an inordinate amount of time to open files.

With no files open for editing, just a project open in the Project Explorer, performing a file search (Eclipse menu Search/File...) and then selecting one of the files to open from the search results, it can sometimes take 2 or 3 minutes for the file to open. In the meanwhile the mouse cursor (when hovering in the editor area) has gone into a spinning wheel.

I also checked opening files from Project Explorer with no other files open in the editor and the same thing happens: a very long wait until the file opens.

From this it seems that it is nothing to do with Search/File per se, but rather the Language Server is taking a very long time to start when opening a (TypeScript) file for editing.

I don't have permissions to reopen this issue (as you mentioned above). Would you please reopen it @mickaelistria for further rectification.

Thanks.

**Comment by mickaelistria** [comment]
This is IMO a different issue, and will have a different solution. Please open a new ticket with steps to reproduce.
